### ISSUE TITLE
Error in Laravel 5.8

### ISSUE THREAD

**Issue by silasrm** [WhereIsLucas/laravel-bootstrap-toasts#1]
After install, this error occurs:

` Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Call to undefined method WhereIsLucas\LaravelBootstrapToasts\Toaster::isDeferred()`

**Comment by silasrm** [comment]
Fix. Change this:
`'providers' => [
    // ...
    WhereIsLucas\LaravelBootstrapToasts\Toaster::class,
];`
To:

`'providers' => [
    // ...
    WhereIsLucas\LaravelBootstrapToasts\ToastServiceProvider::class,
];`

**Comment by WhereIsLucas** [comment]
Thanks for the input!
