### ISSUE TITLE
Error after install 5.8

### ISSUE THREAD

**Issue by uwejan** [WhereIsLucas/laravel-bootstrap-toasts#2]
![Screenshot from 2019-07-24 16-42-12](https://user-images.githubusercontent.com/20250935/61798587-35757a00-ae32-11e9-8945-3416e59e8715.png)

**Comment by ediblemanager** [comment]
@WhereIsLucas any idea how to fix the above error? I'm experiencing the same.

**Comment by WhereIsLucas** [comment]
I'l look into this in a few days!

**Comment by uwejan** [comment]
@WhereIsLucas any update?

**Comment by WhereIsLucas** [comment]
Hey sorry for the time taken. The issue has been fixed!
See commit #f37c8d4
